name: Build and deploy Node.js app to Azure Web App - my-nodejs-app-sif332

env:
  AZURE_CLIENT_ID: '1bc9ad74-0bbb-4122-9f63-e6866c7028f2'
  AZURE_TENANT_ID: 'afde52eb-b04b-4fb6-b70c-03e341486547'
  AZURE_SUBSCRIPTION_ID: '797b8db6-5f65-480b-a1d7-8e370b37628a'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  azureauth:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: Azure Auth
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-nodejs-app-sif332'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_22aed113b3134ca1a14200c9ad9fe064 }}
          package: .